image: tarunjangra/gi-www:1.4

before_script:
  - bundle install --path vendor/bundle
  - npm install

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor
    - node_modules
    - dist

stages:
  - build
  - artifacts
  - test
  - deploy

Build:
  stage: build
  script:
    - bundle exec rake clean
    - bundle exec rake build
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /deploy/
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - _site/

Test:
  stage: test
  script:
    - bundle exec rake pages
    - bundle exec rake garbage
    - bundle exec rake snippets
    - bundle exec rake spell
    - bundle exec rake regex
    - bundle exec rake excerpts 
    - bundle exec rake ping
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /deploy/

Artifacts:
  stage: artifacts
  script:
    - cd semantic
    - ../node_modules/.bin/gulp build
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /deploy/

Deploy:
  stage: deploy
  script:
    - AWS_ACCESS_KEY_ID=AKIAJCRWQTCAKYKPVL7A AWS_SECRET_ACCESS_KEY=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 java -cp $(bundle show s3_website)/*.jar s3.website.Push
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /deploy/    