dist: trusty
language: ruby
rvm:
- 2.2.7
sudo: required
branches:
  only:
  - master
cache:
  directories:
    - node_modules
    - vendor/bundle
env:
  global:
    secure: 
addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - build-essential
      - graphviz
      - s3cmd
      - gnuplot
      - fontforge
      - liblapack-dev
      - libxml2-utils
before_install:
  - set -e
  - git config --global user.email "tarun@izap.in"
  - git config --global user.name "tarunjangra"
install:
  - set -e
  - bundle
deploy:
  provider: script
  script: 
    - set -e
    - openssl aes-256-cbc -K $encrypted_00bac43a30b4_key -iv $encrypted_00bac43a30b4_iv -in id_rsa.enc -out id_rsa -d
    - mv id_rsa ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - export JEKYLL_ENV=production
    - bundle exec jgd -u git@github.com:abcdevops/blog.git
  on:
    branch: master
    
