language: ruby
rvm:
  - 2.2.7
sudo: required
branches:
  only:
  - master
cache:
  directories:
    - node_modules
    - vendor/bundle
env:
  global:
    secure: 
addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - build-essential
      - graphviz
      - gnuplot
      - s3cmd
      - fontforge
      - liblapack-dev
before_install:
- set -e
- git config user.name "{GIT_UNAME}"
- git config user.email "{GIT_EMAIL}"
- git remote set-url origin git@github.com:abcdevops/abcdevops.github.io.git
- git remote -v
- openssl aes-256-cbc -K $encrypted_185c9067a251_key
- chmod u=rw,og= ~/.ssh/deploy_key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/deploy_key" >> ~/.ssh/config
install:
  - set -e
  - travis_retry sudo _travis/install_cmake.sh; sudo apt-get install -y libxml2-utils
  - travis_retry npm install cssshrink@0.0.5
  - travis_retry sudo _travis/install_plantuml.sh
  - travis_retry sudo _travis/install_sfnt2woff.sh
  - travis_retry sudo _travis/install_tidy.sh
  - travis_retry gem install jekyll-watch -v 2.0.0
  - travis_retry bundle install
  - travis_retry gem install fontcustom -v 1.3.8
  - fontcustom --version
  - travis_retry gem install jgd -v 1.11
  - gnuplot --version
script:
  - set -e
  - bundle exec rake
  - export JEKYLL_ENV=production
  - bundle exec jgd -u git@github.com:abcdevops/abcdevops.github.io.git
