dist: trusty
language: ruby
rvm:
- 2.2.7
sudo: required
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - vendor/bundle
env:
  global:
    secure: 
addons:
  apt:
    packages:
    - aspell
    - aspell-en
    - build-essential
    - graphviz
    - s3cmd
    - gnuplot
    - fontforge
    - liblapack-dev
    - libxml2-utils
before_install:
- set -e
- git config --global user.email "tarun@izap.in"
- git config --global user.name "tarunjangra"
- openssl aes-256-cbc -K $encrypted_00bac43a30b4_key -iv $encrypted_00bac43a30b4_iv
  -in id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh
- chmod 600 ~/.ssh/id_rsa
install:
- set -e
- bundle
- travis_retry sudo _travis/install_cmake.sh
- travis_retry npm install cssshrink@0.0.5
- travis_retry sudo _travis/install_plantuml.sh
- travis_retry sudo _travis/install_sfnt2woff.sh
- travis_retry sudo _travis/install_tidy.sh
- travis_retry gem install jekyll-watch -v 2.0.0
- travis_retry bundle exec fontcustom --version
- gnuplot --version
script:
- set -e
- export JEKYLL_ENV=production
- bundle exec rake
- bundle exec jgd -u git@github.com:abcdevops/blog.git
