dist: trusty
language: ruby
rvm:
  - 2.2.7
sudo: required
branches:
  only:
  - master
cache:
  directories:
    - node_modules
    - vendor/bundle
env:
  global:
    secure: 
addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - build-essential
      - graphviz
      - gnuplot
      - fontforge
      - liblapack-dev
      - libxml2-utils
before_install:
- set -e
- git config --global user.email "tarun@izap.in"
- git config --global user.name "tarunjangra"
install:
  - set -e
  - travis_retry sudo _travis/install_cmake.sh
  - travis_retry npm install cssshrink@0.0.5
  - travis_retry sudo _travis/install_plantuml.sh
  - travis_retry sudo _travis/install_sfnt2woff.sh
  - travis_retry sudo _travis/install_tidy.sh
  - travis_retry gem install jekyll-watch -v 2.0.0
  - travis_retry bundle install
script:
  - set -e
  - bundle exec fontcustom --version
  - bundle exec rake
  - export JEKYLL_ENV=production
  - bundle exec jgd -b master -u https://tarunjangra:$PASSWORD@github.com/abcdevops/abcdevops.github.io.git
  
