name: ABCDevOps
url: https://abcdevops.com
title: "ABCDevOps: re:devining DevOps"
author:
  name: "Tarun Jangra"
  email: tarun.jangra@abcdevops.com
  image: "https://tarunjangra.com/images/about/tarun-jangra-200x200.jpg"
  profile: "http://tarunjangra.com"
description: "ABCDevOps: Let's discuss what devops is."
copyright: "(c) abcdevops, 2019"
encoding: utf-8
timezone: Canada/Eastern
markdown: kramdown
highlighter: pygments
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
permalink: /blog/:year/:month/:day/:title.html
paginate: 10
paginate_path: "/blog/page:num"
excerpt_separator: <!--more-->
exclude:
  - README.md
  - LICENSE.txt
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - httpd.conf
  - id_rsa.enc
  - s3cfg.enc
  - uml
  - node_modules
  - vendor
  - vagrant
  - Vagrantfile
  - semantic
  - bin
  - dist/components
  - dist/semantic.js
  - dist/semantic.css
  - .bundle
  - Makefile
  - package.json
  - package-lock.json
  - semantic.json


featured: 3
img_width: 200
img_height: 200

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-plantuml
  - jekyll-sitemap
  - jekyll-related-posts

# see https://github.com/alfanick/jekyll-related-posts
related:
  max_count: 5
  min_score: 0.1
  accuracy: 0.75

# jekyll-feed
feed:
  title: "ABCDevOps: re:defining devops"
  subtitle: "AWS, Cloud, Azure, GCP, Google, DevOps"
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false

# see https://github.com/pattex/jekyll-tagging
tag_page_layout: tag-index
tag_page_dir: tag

# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  ignore:
    envs: [local]
  blanklines: false